# see https://gitlab.com/fdroid/fdroidserver/-/blob/master/examples/config.yml
repo_name: ReVanced APKs
description: This binary repo is automatically updated with releases from Kryptos-123/revanced-auto-apk

archive_older: 2

local_copy_dir: /fdroid

keystore: keystore.p12
repo_keyalias: repokey
keypass: "160906"
keystorepass: "160906"
