# see https://gitlab.com/fdroid/fdroidserver/-/blob/master/examples/config.yml
repo_name: ReVanced APKs
repo_url: https://kryptos-123.github.io/revanced-auto-apk/fdroid/repo/
description: This binary repo is automatically updated with releases from Kryptos-123/revanced-auto-apk

archive_older: 2

local_copy_dir: /docs/fdroid

keystore: keystore.p12
repo_keyalias: repokey
keystorepass: "yTetvd8F8XXyNBZMEcN"
keypass: "yTetvd8F8XXyNBZMEcN"
