name: Update F-Droid

on: [workflow_call, workflow_dispatch]

jobs:
  nightly:
    name: Update F-Droid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: F-Droid
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install apksigner fdroidserver --no-install-recommends
          cd docs/fdroid
          echo "${{ secrets.KEYSTORE }}" | base64 -d >keystore.p12
          chmod 0600 config.yml
          fdroid update -c --pretty
          fdroid deploy
