name: Update F-Droid

on: [workflow_call, workflow_dispatch]

jobs:
  nightly:
    name: Update F-Droid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: F-Droid
        run: |
          cd docs/fdroid
          echo "${{ secrets.KEYSTORE }}" | base64 -d >keystore.p12
          KEYPASS = ${{ secrets.KEYPASS }}
          echo "keystorepass: $KEYPASS"
          echo "keypass: $KEYPASS"
