name: Update F-Droid

on:
  push:
    branches:
      - main

jobs:
  nightly:
    name: Update F-Droid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: |
          # use timestamp as Version Code
          export versionCode=$(date '+%s')
          sed -i "s,^\(\s*versionCode\)  *[0-9].*,\1 $versionCode," app/build.gradle
          ./gradlew assembleDebug
      - name: F-Droid
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install apksigner fdroidserver --no-install-recommends
          cd docs/fdroid
          echo "${{ secrets.KEYSTORE }}" | base64 -d >keystore.p12
          echo "keystorepass: ${{ secrets.KEYPASS }}" >>config.yml
          echo "keypass: ${{ secrets.KEYPASS }}" >>config.yml
          fdroid update -c --pretty
          fdroid deploy
